name: flutix
description: A Tix id clone.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  auto_route: ^6.4.0

  # DI
  get_it: ^7.3.0
  injectable: ^2.1.1

  freezed: ^2.3.2
  freezed_annotation: ^2.2.0

  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1

  dartz: ^0.10.1

  data_channel: ^2.0.0+1

  json_annotation: ^4.8.0

  #utils
  flutter_dotenv: ^5.0.2
  flutter_image_compress: ^1.1.3
  string_validator: ^1.0.0
  loader_overlay: ^2.2.0
  fluttertoast: ^8.2.2

  #firebase
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  firebase_storage: ^11.1.1
  firebase_core: ^2.10.0

  #notifications
  awesome_notifications: ^0.7.4+1
  awesome_notifications_fcm: ^0.7.4+1

  equatable: ^2.0.5
  provider: ^6.0.5
  flutter_bloc: ^8.1.2
  google_fonts: ^4.0.4
  email_validator: ^2.1.17
  another_flushbar: ^1.12.29
  flutter_spinkit: ^5.2.0
  material_design_icons_flutter: ^6.0.7096
  intl: ^0.17.0
  image_picker: ^0.8.7+4
  http: ^0.13.6
  random_string: ^2.3.1
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.5
  auto_route_generator: ^6.2.0
  flutter_gen_runner: ^5.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_gen:
  output: lib/presentation/components/gen

  colors:
    inputs:
      - assets/colors/color.xml